// Code generated by "stringer -type=JobStatus"; DO NOT EDIT

package rumpacker

import "fmt"

const _JobStatus_name = "InitialisedAMI_DetachingAMI_SnapshottingAMI_CreatingImageAMI_RegisteringImageAMI_AttachingDoneErroredAttach_AWS_volume"

var _JobStatus_index = [...]uint8{0, 11, 24, 40, 57, 77, 90, 94, 101, 118}

func (i JobStatus) String() string {
	if i < 0 || i >= JobStatus(len(_JobStatus_index)-1) {
		return fmt.Sprintf("JobStatus(%d)", i)
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
