// Code generated by "stringer -type=RumpackerState"; DO NOT EDIT

package state

import "fmt"

const _RumpackerState_name = "Rumpacker_InitialisedAMI_DetachingAMI_SnapshottingAMI_CreatingImageAMI_RegisteringImageAMI_AttachingRumpacker_DoneRumpacker_ErroredAttach_AWS_volume"

var _RumpackerState_index = [...]uint8{0, 21, 34, 50, 67, 87, 100, 114, 131, 148}

func (i RumpackerState) String() string {
	if i < 0 || i >= RumpackerState(len(_RumpackerState_index)-1) {
		return fmt.Sprintf("RumpackerState(%d)", i)
	}
	return _RumpackerState_name[_RumpackerState_index[i]:_RumpackerState_index[i+1]]
}
