// Code generated by "stringer -type=RumpackerState"; DO NOT EDIT

package state

import "fmt"

const _RumpackerState_name = "InitialisedAMI_DetachingAMI_SnapshottingAMI_CreatingImageAMI_RegisteringImageAMI_AttachingDoneErroredAttach_AWS_volume"

var _RumpackerState_index = [...]uint8{0, 11, 24, 40, 57, 77, 90, 94, 101, 118}

func (i RumpackerState) String() string {
	if i < 0 || i >= RumpackerState(len(_RumpackerState_index)-1) {
		return fmt.Sprintf("RumpackerState(%d)", i)
	}
	return _RumpackerState_name[_RumpackerState_index[i]:_RumpackerState_index[i+1]]
}
